In [4]:
!pip install mlflow

Collecting mlflow
  Downloading mlflow-3.10.1-py3-none-any.whl.metadata (31 kB)
Collecting mlflow-skinny==3.10.1 (from mlflow)
  Downloading mlflow_skinny-3.10.1-py3-none-any.whl.metadata (32 kB)
Collecting mlflow-tracing==3.10.1 (from mlflow)
  Downloading mlflow_tracing-3.10.1-py3-none-any.whl.metadata (19 kB)
Collecting Flask-CORS<7 (from mlflow)
  Using cached flask_cors-6.0.2-py3-none-any.whl.metadata (5.3 kB)
Collecting Flask<4 (from mlflow)
  Downloading flask-3.1.3-py3-none-any.whl.metadata (3.2 kB)
Collecting alembic!=1.10.0,<2 (from mlflow)
  Downloading alembic-1.18.4-py3-none-any.whl.metadata (7.2 kB)
Collecting cryptography<47,>=43.0.0 (from mlflow)
  Downloading cryptography-46.0.5-cp38-abi3-win_amd64.whl.metadata (5.7 kB)
Collecting docker<8,>=4.0.0 (from mlflow)
  Using cached docker-7.1.0-py3-none-any.whl.metadata (3.8 kB)
Collecting graphene<4 (from mlflow)
  Using cached graphene-3.4.3-py2.py3-none-any.whl.metadata (6.9 kB)
Collecting huey<3,>=2.5.4 (from mlflow)
  Downloading huey-2.6.0-py3-none-any.whl.metadata (4.3 kB)
Collecting matplotlib<4 (from mlflow)
  Using cached matplotlib-3.10.8-cp310-cp310-win_amd64.whl.metadata (52 kB)
Requirement already satisfied: numpy<3 in c:\users\arupa\.conda\envs\atlas\lib\site-packages (from mlflow) (2.2.6)
Requirement already satisfied: pandas<3 in c:\users\arupa\.conda\envs\atlas\lib\site-packages (from mlflow) (2.3.3)
Collecting pyarrow<24,>=4.0.0 (from mlflow)
  Downloading pyarrow-23.0.1-cp310-cp310-win_amd64.whl.metadata (3.1 kB)
Collecting scikit-learn<2 (from mlflow)
  Using cached scikit_learn-1.7.2-cp310-cp310-win_amd64.whl.metadata (11 kB)
Collecting scipy<2 (from mlflow)
  Using cached scipy-1.15.3-cp310-cp310-win_amd64.whl.metadata (60 kB)
Collecting skops<1 (from mlflow)
  Downloading skops-0.13.0-py3-none-any.whl.metadata (5.6 kB)
Collecting sqlalchemy<3,>=1.4.0 (from mlflow)
  Downloading sqlalchemy-2.0.48-cp310-cp310-win_amd64.whl.metadata (9.8 kB)
Collecting waitress<4 (from mlflow)
  Using cached waitress-3.0.2-py3-none-any.whl.metadata (5.8 kB)
Collecting cachetools<8,>=5.0.0 (from mlflow-skinny==3.10.1->mlflow)
  Downloading cachetools-7.0.5-py3-none-any.whl.metadata (5.6 kB)
Requirement already satisfied: click<9,>=7.0 in c:\users\arupa\.conda\envs\atlas\lib\site-packages (from mlflow-skinny==3.10.1->mlflow) (8.3.1)
Collecting cloudpickle<4 (from mlflow-skinny==3.10.1->mlflow)
  Using cached cloudpickle-3.1.2-py3-none-any.whl.metadata (7.1 kB)
Collecting databricks-sdk<1,>=0.20.0 (from mlflow-skinny==3.10.1->mlflow)
  Downloading databricks_sdk-0.98.0-py3-none-any.whl.metadata (40 kB)
Collecting fastapi<1 (from mlflow-skinny==3.10.1->mlflow)
  Downloading fastapi-0.135.1-py3-none-any.whl.metadata (30 kB)
Requirement already satisfied: gitpython<4,>=3.1.9 in c:\users\arupa\.conda\envs\atlas\lib\site-packages (from mlflow-skinny==3.10.1->mlflow) (3.1.46)
Collecting importlib_metadata!=4.7.0,<9,>=3.7.0 (from mlflow-skinny==3.10.1->mlflow)
  Using cached importlib_metadata-8.7.1-py3-none-any.whl.metadata (4.7 kB)
Collecting opentelemetry-api<3,>=1.9.0 (from mlflow-skinny==3.10.1->mlflow)
  Downloading opentelemetry_api-1.40.0-py3-none-any.whl.metadata (1.5 kB)
Collecting opentelemetry-proto<3,>=1.9.0 (from mlflow-skinny==3.10.1->mlflow)
  Downloading opentelemetry_proto-1.40.0-py3-none-any.whl.metadata (2.4 kB)
Collecting opentelemetry-sdk<3,>=1.9.0 (from mlflow-skinny==3.10.1->mlflow)
  Downloading opentelemetry_sdk-1.40.0-py3-none-any.whl.metadata (1.6 kB)
Requirement already satisfied: packaging<27 in c:\users\arupa\.conda\envs\atlas\lib\site-packages (from mlflow-skinny==3.10.1->mlflow) (25.0)
Collecting protobuf<7,>=3.12.0 (from mlflow-skinny==3.10.1->mlflow)
  Downloading protobuf-6.33.5-cp310-abi3-win_amd64.whl.metadata (593 bytes)
Requirement already satisfied: pydantic<3,>=2.0.0 in c:\users\arupa\.conda\envs\atlas\lib\site-packages (from mlflow-skinny==3.10.1->mlflow) (2.12.5)
Collecting python-dotenv<2,>=0.19.0 (from mlflow-skinny==3.10.1->mlflow)
  Downloading python_dotenv-1.2.2-py3-none-any.whl.metadata (27 kB)
Requirement already satisfied: pyyaml<7,>=5.1 in c:\users\arupa\.conda\envs\atlas\lib\site-packages (from mlflow-skinny==3.10.1->mlflow) (6.0.3)
Requirement already satisfied: requests<3,>=2.17.3 in c:\users\arupa\.conda\envs\atlas\lib\site-packages (from mlflow-skinny==3.10.1->mlflow) (2.32.5)
Collecting sqlparse<1,>=0.4.0 (from mlflow-skinny==3.10.1->mlflow)
  Downloading sqlparse-0.5.5-py3-none-any.whl.metadata (4.7 kB)
Requirement already satisfied: typing-extensions<5,>=4.0.0 in c:\users\arupa\.conda\envs\atlas\lib\site-packages (from mlflow-skinny==3.10.1->mlflow) (4.15.0)
Collecting uvicorn<1 (from mlflow-skinny==3.10.1->mlflow)
  Downloading uvicorn-0.41.0-py3-none-any.whl.metadata (6.7 kB)
Collecting Mako (from alembic!=1.10.0,<2->mlflow)
  Downloading mako-1.3.10-py3-none-any.whl.metadata (2.9 kB)
Collecting tomli (from alembic!=1.10.0,<2->mlflow)
  Downloading tomli-2.4.0-py3-none-any.whl.metadata (10 kB)
Requirement already satisfied: colorama in c:\users\arupa\.conda\envs\atlas\lib\site-packages (from click<9,>=7.0->mlflow-skinny==3.10.1->mlflow) (0.4.6)
Collecting cffi>=2.0.0 (from cryptography<47,>=43.0.0->mlflow)
  Downloading cffi-2.0.0-cp310-cp310-win_amd64.whl.metadata (2.6 kB)
Collecting google-auth~=2.0 (from databricks-sdk<1,>=0.20.0->mlflow-skinny==3.10.1->mlflow)
  Downloading google_auth-2.49.0-py3-none-any.whl.metadata (6.2 kB)
Requirement already satisfied: pywin32>=304 in c:\users\arupa\.conda\envs\atlas\lib\site-packages (from docker<8,>=4.0.0->mlflow) (311)
Requirement already satisfied: urllib3>=1.26.0 in c:\users\arupa\.conda\envs\atlas\lib\site-packages (from docker<8,>=4.0.0->mlflow) (2.6.3)
Collecting starlette>=0.46.0 (from fastapi<1->mlflow-skinny==3.10.1->mlflow)
  Downloading starlette-0.52.1-py3-none-any.whl.metadata (6.3 kB)
Requirement already satisfied: typing-inspection>=0.4.2 in c:\users\arupa\.conda\envs\atlas\lib\site-packages (from fastapi<1->mlflow-skinny==3.10.1->mlflow) (0.4.2)
Collecting annotated-doc>=0.0.2 (from fastapi<1->mlflow-skinny==3.10.1->mlflow)
  Using cached annotated_doc-0.0.4-py3-none-any.whl.metadata (6.6 kB)
Collecting blinker>=1.9.0 (from Flask<4->mlflow)
  Using cached blinker-1.9.0-py3-none-any.whl.metadata (1.6 kB)
Collecting itsdangerous>=2.2.0 (from Flask<4->mlflow)
  Using cached itsdangerous-2.2.0-py3-none-any.whl.metadata (1.9 kB)
Collecting jinja2>=3.1.2 (from Flask<4->mlflow)
  Using cached jinja2-3.1.6-py3-none-any.whl.metadata (2.9 kB)
Collecting markupsafe>=2.1.1 (from Flask<4->mlflow)
  Using cached markupsafe-3.0.3-cp310-cp310-win_amd64.whl.metadata (2.8 kB)
Collecting werkzeug>=3.1.0 (from Flask<4->mlflow)
  Downloading werkzeug-3.1.6-py3-none-any.whl.metadata (4.0 kB)
Requirement already satisfied: gitdb<5,>=4.0.1 in c:\users\arupa\.conda\envs\atlas\lib\site-packages (from gitpython<4,>=3.1.9->mlflow-skinny==3.10.1->mlflow) (4.0.12)
Requirement already satisfied: smmap<6,>=3.0.1 in c:\users\arupa\.conda\envs\atlas\lib\site-packages (from gitdb<5,>=4.0.1->gitpython<4,>=3.1.9->mlflow-skinny==3.10.1->mlflow) (5.0.3)
Collecting pyasn1-modules>=0.2.1 (from google-auth~=2.0->databricks-sdk<1,>=0.20.0->mlflow-skinny==3.10.1->mlflow)
  Downloading pyasn1_modules-0.4.2-py3-none-any.whl.metadata (3.5 kB)
Collecting rsa<5,>=3.1.4 (from google-auth~=2.0->databricks-sdk<1,>=0.20.0->mlflow-skinny==3.10.1->mlflow)
  Downloading rsa-4.9.1-py3-none-any.whl.metadata (5.6 kB)
Requirement already satisfied: graphql-core<3.3,>=3.1 in c:\users\arupa\.conda\envs\atlas\lib\site-packages (from graphene<4->mlflow) (3.2.8)
Collecting graphql-relay<3.3,>=3.1 (from graphene<4->mlflow)
  Using cached graphql_relay-3.2.0-py3-none-any.whl.metadata (12 kB)
Requirement already satisfied: python-dateutil<3,>=2.7.0 in c:\users\arupa\.conda\envs\atlas\lib\site-packages (from graphene<4->mlflow) (2.9.0.post0)
Collecting zipp>=3.20 (from importlib_metadata!=4.7.0,<9,>=3.7.0->mlflow-skinny==3.10.1->mlflow)
  Using cached zipp-3.23.0-py3-none-any.whl.metadata (3.6 kB)
Collecting contourpy>=1.0.1 (from matplotlib<4->mlflow)
  Using cached contourpy-1.3.2-cp310-cp310-win_amd64.whl.metadata (5.5 kB)
Collecting cycler>=0.10 (from matplotlib<4->mlflow)
  Using cached cycler-0.12.1-py3-none-any.whl.metadata (3.8 kB)
Collecting fonttools>=4.22.0 (from matplotlib<4->mlflow)
  Downloading fonttools-4.62.0-cp310-cp310-win_amd64.whl.metadata (119 kB)
Collecting kiwisolver>=1.3.1 (from matplotlib<4->mlflow)
  Downloading kiwisolver-1.5.0-cp310-cp310-win_amd64.whl.metadata (5.2 kB)
Requirement already satisfied: pillow>=8 in c:\users\arupa\.conda\envs\atlas\lib\site-packages (from matplotlib<4->mlflow) (12.1.1)
Collecting pyparsing>=3 (from matplotlib<4->mlflow)
  Using cached pyparsing-3.3.2-py3-none-any.whl.metadata (5.8 kB)
Collecting opentelemetry-semantic-conventions==0.61b0 (from opentelemetry-sdk<3,>=1.9.0->mlflow-skinny==3.10.1->mlflow)
  Downloading opentelemetry_semantic_conventions-0.61b0-py3-none-any.whl.metadata (2.5 kB)
Requirement already satisfied: pytz>=2020.1 in c:\users\arupa\.conda\envs\atlas\lib\site-packages (from pandas<3->mlflow) (2026.1.post1)
Requirement already satisfied: tzdata>=2022.7 in c:\users\arupa\.conda\envs\atlas\lib\site-packages (from pandas<3->mlflow) (2025.3)
Requirement already satisfied: annotated-types>=0.6.0 in c:\users\arupa\.conda\envs\atlas\lib\site-packages (from pydantic<3,>=2.0.0->mlflow-skinny==3.10.1->mlflow) (0.7.0)
Requirement already satisfied: pydantic-core==2.41.5 in c:\users\arupa\.conda\envs\atlas\lib\site-packages (from pydantic<3,>=2.0.0->mlflow-skinny==3.10.1->mlflow) (2.41.5)
Requirement already satisfied: six>=1.5 in c:\users\arupa\.conda\envs\atlas\lib\site-packages (from python-dateutil<3,>=2.7.0->graphene<4->mlflow) (1.17.0)
Requirement already satisfied: charset_normalizer<4,>=2 in c:\users\arupa\.conda\envs\atlas\lib\site-packages (from requests<3,>=2.17.3->mlflow-skinny==3.10.1->mlflow) (3.4.5)
Requirement already satisfied: idna<4,>=2.5 in c:\users\arupa\.conda\envs\atlas\lib\site-packages (from requests<3,>=2.17.3->mlflow-skinny==3.10.1->mlflow) (3.11)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\arupa\.conda\envs\atlas\lib\site-packages (from requests<3,>=2.17.3->mlflow-skinny==3.10.1->mlflow) (2026.2.25)
Collecting pyasn1>=0.1.3 (from rsa<5,>=3.1.4->google-auth~=2.0->databricks-sdk<1,>=0.20.0->mlflow-skinny==3.10.1->mlflow)
  Downloading pyasn1-0.6.2-py3-none-any.whl.metadata (8.4 kB)
Collecting joblib>=1.2.0 (from scikit-learn<2->mlflow)
  Using cached joblib-1.5.3-py3-none-any.whl.metadata (5.5 kB)
Collecting threadpoolctl>=3.1.0 (from scikit-learn<2->mlflow)
  Using cached threadpoolctl-3.6.0-py3-none-any.whl.metadata (13 kB)
Collecting prettytable>=3.9 (from skops<1->mlflow)
  Downloading prettytable-3.17.0-py3-none-any.whl.metadata (34 kB)
Collecting greenlet>=1 (from sqlalchemy<3,>=1.4.0->mlflow)
  Downloading greenlet-3.3.2-cp310-cp310-win_amd64.whl.metadata (3.8 kB)
Requirement already satisfied: h11>=0.8 in c:\users\arupa\.conda\envs\atlas\lib\site-packages (from uvicorn<1->mlflow-skinny==3.10.1->mlflow) (0.16.0)
Collecting pycparser (from cffi>=2.0.0->cryptography<47,>=43.0.0->mlflow)
  Downloading pycparser-3.0-py3-none-any.whl.metadata (8.2 kB)
Requirement already satisfied: wcwidth in c:\users\arupa\.conda\envs\atlas\lib\site-packages (from prettytable>=3.9->skops<1->mlflow) (0.6.0)
Requirement already satisfied: anyio<5,>=3.6.2 in c:\users\arupa\.conda\envs\atlas\lib\site-packages (from starlette>=0.46.0->fastapi<1->mlflow-skinny==3.10.1->mlflow) (4.12.1)
Requirement already satisfied: exceptiongroup>=1.0.2 in c:\users\arupa\.conda\envs\atlas\lib\site-packages (from anyio<5,>=3.6.2->starlette>=0.46.0->fastapi<1->mlflow-skinny==3.10.1->mlflow) (1.3.1)
Downloading mlflow-3.10.1-py3-none-any.whl (10.2 MB)
   ---------------------------------------- 0.0/10.2 MB ? eta -:--:--
   -- ------------------------------------- 0.5/10.2 MB 3.3 MB/s eta 0:00:03
   ----- ---------------------------------- 1.3/10.2 MB 3.9 MB/s eta 0:00:03
   --------- ------------------------------ 2.4/10.2 MB 4.3 MB/s eta 0:00:02
   ------------- -------------------------- 3.4/10.2 MB 4.4 MB/s eta 0:00:02
   ----------------- ---------------------- 4.5/10.2 MB 4.5 MB/s eta 0:00:02
   --------------------- ------------------ 5.5/10.2 MB 4.5 MB/s eta 0:00:02
   ------------------------- -------------- 6.6/10.2 MB 4.6 MB/s eta 0:00:01
   ----------------------------- ---------- 7.6/10.2 MB 4.7 MB/s eta 0:00:01
   ----------------------------------- ---- 8.9/10.2 MB 4.8 MB/s eta 0:00:01
   ---------------------------------------  10.0/10.2 MB 4.8 MB/s eta 0:00:01
   ---------------------------------------- 10.2/10.2 MB 4.8 MB/s  0:00:02
Downloading mlflow_skinny-3.10.1-py3-none-any.whl (3.0 MB)
   ---------------------------------------- 0.0/3.0 MB ? eta -:--:--
   -------------- ------------------------- 1.0/3.0 MB 5.6 MB/s eta 0:00:01
   ------------------------ --------------- 1.8/3.0 MB 5.3 MB/s eta 0:00:01
   ---------------------------------------- 3.0/3.0 MB 4.8 MB/s  0:00:00
Downloading mlflow_tracing-3.10.1-py3-none-any.whl (1.5 MB)
   ---------------------------------------- 0.0/1.5 MB ? eta -:--:--
   --------------------- ------------------ 0.8/1.5 MB 3.7 MB/s eta 0:00:01
   ---------------------------------------- 1.5/1.5 MB 4.0 MB/s  0:00:00
Downloading alembic-1.18.4-py3-none-any.whl (263 kB)
Downloading cachetools-7.0.5-py3-none-any.whl (13 kB)
Using cached cloudpickle-3.1.2-py3-none-any.whl (22 kB)
Downloading cryptography-46.0.5-cp38-abi3-win_amd64.whl (3.5 MB)
   ---------------------------------------- 0.0/3.5 MB ? eta -:--:--
   --------- ------------------------------ 0.8/3.5 MB 4.2 MB/s eta 0:00:01
   --------------------- ------------------ 1.8/3.5 MB 4.4 MB/s eta 0:00:01
   ------------------------------ --------- 2.6/3.5 MB 4.4 MB/s eta 0:00:01
   ---------------------------------------- 3.5/3.5 MB 4.3 MB/s  0:00:00
Downloading databricks_sdk-0.98.0-py3-none-any.whl (828 kB)
   ---------------------------------------- 0.0/828.0 kB ? eta -:--:--
   ---------------------------------------- 828.0/828.0 kB 4.0 MB/s  0:00:00
Using cached docker-7.1.0-py3-none-any.whl (147 kB)
Downloading fastapi-0.135.1-py3-none-any.whl (116 kB)
Downloading flask-3.1.3-py3-none-any.whl (103 kB)
Using cached flask_cors-6.0.2-py3-none-any.whl (13 kB)
Downloading google_auth-2.49.0-py3-none-any.whl (240 kB)
Using cached graphene-3.4.3-py2.py3-none-any.whl (114 kB)
Using cached graphql_relay-3.2.0-py3-none-any.whl (16 kB)
Downloading huey-2.6.0-py3-none-any.whl (76 kB)
Using cached importlib_metadata-8.7.1-py3-none-any.whl (27 kB)
Using cached matplotlib-3.10.8-cp310-cp310-win_amd64.whl (8.1 MB)
Downloading opentelemetry_api-1.40.0-py3-none-any.whl (68 kB)
Downloading opentelemetry_proto-1.40.0-py3-none-any.whl (72 kB)
Downloading opentelemetry_sdk-1.40.0-py3-none-any.whl (141 kB)
Downloading opentelemetry_semantic_conventions-0.61b0-py3-none-any.whl (231 kB)
Downloading protobuf-6.33.5-cp310-abi3-win_amd64.whl (437 kB)
Downloading pyarrow-23.0.1-cp310-cp310-win_amd64.whl (27.5 MB)
   ---------------------------------------- 0.0/27.5 MB ? eta -:--:--
   - -------------------------------------- 0.8/27.5 MB 4.8 MB/s eta 0:00:06
   -- ------------------------------------- 1.8/27.5 MB 4.6 MB/s eta 0:00:06
   ---- ----------------------------------- 2.9/27.5 MB 4.5 MB/s eta 0:00:06
   ----- ---------------------------------- 3.7/27.5 MB 4.5 MB/s eta 0:00:06
   ------ --------------------------------- 4.7/27.5 MB 4.6 MB/s eta 0:00:05
   -------- ------------------------------- 5.8/27.5 MB 4.5 MB/s eta 0:00:05
   --------- ------------------------------ 6.6/27.5 MB 4.6 MB/s eta 0:00:05
   ----------- ---------------------------- 7.6/27.5 MB 4.4 MB/s eta 0:00:05
   ----------- ---------------------------- 8.1/27.5 MB 4.4 MB/s eta 0:00:05
   ------------ --------------------------- 8.9/27.5 MB 4.3 MB/s eta 0:00:05
   -------------- ------------------------- 10.0/27.5 MB 4.3 MB/s eta 0:00:05
   --------------- ------------------------ 10.7/27.5 MB 4.2 MB/s eta 0:00:04
   ---------------- ----------------------- 11.5/27.5 MB 4.2 MB/s eta 0:00:04
   ------------------ --------------------- 12.6/27.5 MB 4.2 MB/s eta 0:00:04
   ------------------- -------------------- 13.4/27.5 MB 4.2 MB/s eta 0:00:04
   -------------------- ------------------- 14.2/27.5 MB 4.2 MB/s eta 0:00:04
   ---------------------- ----------------- 15.2/27.5 MB 4.2 MB/s eta 0:00:03
   ----------------------- ---------------- 16.3/27.5 MB 4.2 MB/s eta 0:00:03
   ------------------------- -------------- 17.3/27.5 MB 4.3 MB/s eta 0:00:03
   -------------------------- ------------- 18.4/27.5 MB 4.3 MB/s eta 0:00:03
   --------------------------- ------------ 19.1/27.5 MB 4.3 MB/s eta 0:00:02
   ----------------------------- ---------- 20.2/27.5 MB 4.3 MB/s eta 0:00:02
   ------------------------------ --------- 21.2/27.5 MB 4.3 MB/s eta 0:00:02
   -------------------------------- ------- 22.3/27.5 MB 4.4 MB/s eta 0:00:02
   --------------------------------- ------ 23.3/27.5 MB 4.4 MB/s eta 0:00:01
   ----------------------------------- ---- 24.1/27.5 MB 4.4 MB/s eta 0:00:01
   ------------------------------------ --- 25.2/27.5 MB 4.4 MB/s eta 0:00:01
   -------------------------------------- - 26.2/27.5 MB 4.4 MB/s eta 0:00:01
   ---------------------------------------  27.3/27.5 MB 4.4 MB/s eta 0:00:01
   ---------------------------------------  27.3/27.5 MB 4.4 MB/s eta 0:00:01
   ---------------------------------------  27.3/27.5 MB 4.4 MB/s eta 0:00:01
   ---------------------------------------- 27.5/27.5 MB 4.1 MB/s  0:00:06
Downloading python_dotenv-1.2.2-py3-none-any.whl (22 kB)
Downloading rsa-4.9.1-py3-none-any.whl (34 kB)
Using cached scikit_learn-1.7.2-cp310-cp310-win_amd64.whl (8.9 MB)
Using cached scipy-1.15.3-cp310-cp310-win_amd64.whl (41.3 MB)
Downloading skops-0.13.0-py3-none-any.whl (131 kB)
Downloading sqlalchemy-2.0.48-cp310-cp310-win_amd64.whl (2.1 MB)
   ---------------------------------------- 0.0/2.1 MB ? eta -:--:--
   -------------- ------------------------- 0.8/2.1 MB 4.8 MB/s eta 0:00:01
   ----------------------------- ---------- 1.6/2.1 MB 4.2 MB/s eta 0:00:01
   ---------------------------------------- 2.1/2.1 MB 3.8 MB/s  0:00:00
Downloading sqlparse-0.5.5-py3-none-any.whl (46 kB)
Downloading uvicorn-0.41.0-py3-none-any.whl (68 kB)
Using cached waitress-3.0.2-py3-none-any.whl (56 kB)
Using cached annotated_doc-0.0.4-py3-none-any.whl (5.3 kB)
Using cached blinker-1.9.0-py3-none-any.whl (8.5 kB)
Downloading cffi-2.0.0-cp310-cp310-win_amd64.whl (182 kB)
Using cached contourpy-1.3.2-cp310-cp310-win_amd64.whl (221 kB)
Using cached cycler-0.12.1-py3-none-any.whl (8.3 kB)
Downloading fonttools-4.62.0-cp310-cp310-win_amd64.whl (1.6 MB)
   ---------------------------------------- 0.0/1.6 MB ? eta -:--:--
   -------------------- ------------------- 0.8/1.6 MB 5.6 MB/s eta 0:00:01
   ---------------------------------------- 1.6/1.6 MB 3.9 MB/s  0:00:00
Downloading greenlet-3.3.2-cp310-cp310-win_amd64.whl (230 kB)
Using cached itsdangerous-2.2.0-py3-none-any.whl (16 kB)
Using cached jinja2-3.1.6-py3-none-any.whl (134 kB)
Using cached joblib-1.5.3-py3-none-any.whl (309 kB)
Downloading kiwisolver-1.5.0-cp310-cp310-win_amd64.whl (73 kB)
Using cached markupsafe-3.0.3-cp310-cp310-win_amd64.whl (15 kB)
Downloading prettytable-3.17.0-py3-none-any.whl (34 kB)
Downloading pyasn1-0.6.2-py3-none-any.whl (83 kB)
Downloading pyasn1_modules-0.4.2-py3-none-any.whl (181 kB)
Using cached pyparsing-3.3.2-py3-none-any.whl (122 kB)
Downloading starlette-0.52.1-py3-none-any.whl (74 kB)
Using cached threadpoolctl-3.6.0-py3-none-any.whl (18 kB)
Downloading werkzeug-3.1.6-py3-none-any.whl (225 kB)
Using cached zipp-3.23.0-py3-none-any.whl (10 kB)
Downloading mako-1.3.10-py3-none-any.whl (78 kB)
Downloading pycparser-3.0-py3-none-any.whl (48 kB)

In [6]:
!pip install nltk

Collecting nltk
  Downloading nltk-3.9.3-py3-none-any.whl.metadata (3.2 kB)
Requirement already satisfied: click in c:\users\arupa\.conda\envs\atlas\lib\site-packages (from nltk) (8.3.1)
Requirement already satisfied: joblib in c:\users\arupa\.conda\envs\atlas\lib\site-packages (from nltk) (1.5.3)
Collecting regex>=2021.8.3 (from nltk)
  Downloading regex-2026.2.28-cp310-cp310-win_amd64.whl.metadata (41 kB)
Collecting tqdm (from nltk)
  Downloading tqdm-4.67.3-py3-none-any.whl.metadata (57 kB)
Requirement already satisfied: colorama in c:\users\arupa\.conda\envs\atlas\lib\site-packages (from click->nltk) (0.4.6)
Downloading nltk-3.9.3-py3-none-any.whl (1.5 MB)
   ---------------------------------------- 0.0/1.5 MB ? eta -:--:--
   -------------------- ------------------- 0.8/1.5 MB 5.6 MB/s eta 0:00:01
   ---------------------------------------- 1.5/1.5 MB 7.3 MB/s  0:00:00
Downloading regex-2026.2.28-cp310-cp310-win_amd64.whl (277 kB)
Downloading tqdm-4.67.3-py3-none-any.whl (78 kB)
Installing collected packages: tqdm, regex, nltk

   ---------------------------------------- 0/3 [tqdm]
   ---------------------------------------- 0/3 [tqdm]
   ---------------------------------------- 0/3 [tqdm]
   ---------------------------------------- 0/3 [tqdm]
   ---------------------------------------- 0/3 [tqdm]
   ------------- -------------------------- 1/3 [regex]
   ------------- -------------------------- 1/3 [regex]
   -------------------------- ------------- 2/3 [nltk]
   -------------------------- ------------- 2/3 [nltk]
   -------------------------- ------------- 2/3 [nltk]
   -------------------------- ------------- 2/3 [nltk]
   -------------------------- ------------- 2/3 [nltk]
   -------------------------- ------------- 2/3 [nltk]
   -------------------------- ------------- 2/3 [nltk]
   -------------------------- ------------- 2/3 [nltk]
   -------------------------- ------------- 2/3 [nltk]
   -------------------------- ------------- 2/3 [nltk]
   -------------------------- ------------- 2/3 [nltk]
   -------------------------- ------------- 2/3 [nltk]
   -------------------------- ------------- 2/3 [nltk]
   -------------------------- ------------- 2/3 [nltk]
   -------------------------- ------------- 2/3 [nltk]
   -------------------------- ------------- 2/3 [nltk]
   -------------------------- ------------- 2/3 [nltk]
   -------------------------- ------------- 2/3 [nltk]
   -------------------------- ------------- 2/3 [nltk]
   -------------------------- ------------- 2/3 [nltk]
   -------------------------- ------------- 2/3 [nltk]
   -------------------------- ------------- 2/3 [nltk]
   -------------------------- ------------- 2/3 [nltk]
   -------------------------- ------------- 2/3 [nltk]
   -------------------------- ------------- 2/3 [nltk]
   -------------------------- ------------- 2/3 [nltk]
   -------------------------- ------------- 2/3 [nltk]
   -------------------------- ------------- 2/3 [nltk]
   -------------------------- ------------- 2/3 [nltk]
   -------------------------- ------------- 2/3 [nltk]
   -------------------------- ------------- 2/3 [nltk]
   -------------------------- ------------- 2/3 [nltk]
   -------------------------- ------------- 2/3 [nltk]
   -------------------------- ------------- 2/3 [nltk]
   -------------------------- ------------- 2/3 [nltk]
   -------------------------- ------------- 2/3 [nltk]
   -------------------------- ------------- 2/3 [nltk]
   -------------------------- ------------- 2/3 [nltk]
   -------------------------- ------------- 2/3 [nltk]
   -------------------------- ------------- 2/3 [nltk]
   -------------------------- ------------- 2/3 [nltk]
   -------------------------- ------------- 2/3 [nltk]
   -------------------------- ------------- 2/3 [nltk]
   -------------------------- ------------- 2/3 [nltk]
   -------------------------- ------------- 2/3 [nltk]
   -------------------------- ------------- 2/3 [nltk]
   -------------------------- ------------- 2/3 [nltk]
   -------------------------- ------------- 2/3 [nltk]
   -------------------------- ------------- 2/3 [nltk]
   -------------------------- ------------- 2/3 [nltk]
   -------------------------- ------------- 2/3 [nltk]
   -------------------------- ------------- 2/3 [nltk]
   -------------------------- ------------- 2/3 [nltk]
   -------------------------- ------------- 2/3 [nltk]
   -------------------------- ------------- 2/3 [nltk]
   -------------------------- ------------- 2/3 [nltk]
   -------------------------- ------------- 2/3 [nltk]
   -------------------------- ------------- 2/3 [nltk]
   -------------------------- ------------- 2/3 [nltk]
   -------------------------- ------------- 2/3 [nltk]
   -------------------------- ------------- 2/3 [nltk]
   -------------------------- ------------- 2/3 [nltk]
   -------------------------- ------------- 2/3 [nltk]
   -------------------------- ------------- 2/3 [nltk]
   -------------------------- ------------- 2/3 [nltk]
   -------------------------- ------------- 2/3 [nltk]
   -------------------------- ------------- 2/3 [nltk]
   -------------------------- ------------- 2/3 [nltk]
   -------------------------- ------------- 2/3 [nltk]
   -------------------------- ------------- 2/3 [nltk]
   -------------------------- ------------- 2/3 [nltk]
   -------------------------- ------------- 2/3 [nltk]
   -------------------------- ------------- 2/3 [nltk]
   -------------------------- ------------- 2/3 [nltk]
   ---------------------------------------- 3/3 [nltk]

Successfully installed nltk-3.9.3 regex-2026.2.28 tqdm-4.67.3

In [7]:
import mlflow
import pandas as pd
import mlflow.sklearn
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score
import pandas as pd
import re
import string
from nltk.corpus import stopwords
from nltk.stem import WordNetLemmatizer
import numpy as np

In [18]:
import nltk
nltk.download('wordnet')
nltk.download('omw-1.4')  # optional, but improves lemmatization

[nltk_data] Downloading package wordnet to
[nltk_data]     C:\Users\arupa\AppData\Roaming\nltk_data...
[nltk_data] Downloading package omw-1.4 to
[nltk_data]     C:\Users\arupa\AppData\Roaming\nltk_data...

True

In [31]:
df = pd.read_csv('IMDB.csv')
df = df.sample(500)
df.to_csv('data.csv', index=False)
df.head()

                                                review sentiment
868  The movie is good and I think Tiffany Amber is...  positive
342  I see that C. Thomas Howell has appeared in ma...  negative
460  1989 was already a year in where Eddie Murphy ...  negative
609  1st watched 12/24/2009  4 out of 10 (Dir-Robe...  negative
708  I've been looking forward to the release of th...  positive

In [32]:
#data_preprocessing
def lemmatization(text):
    lemmatizer = WordNetLemmatizer()
    text = text.split()
    text = [lemmatizer.lemmatize(word) for word in text]
    return " ".join(text)

def remove_stop_words(text):
    stop_words = set(stopwords.words("english"))
    text = [word for word in str(text).split() if word not in stop_words]
    return " ".join(text)

def remove_numbers(text):
    text = ''.join([char for char in text if not char.isdigit()])
    return text

def lower_case(text):
    text = text.split()
    text = [word.lower() for word in text]
    return " ".join(text)

def remove_punctuations(text):
    text = re.sub('[%s]' % re.escape(string.punctuation), ' ', text)
    text = text.replace('؛', "")
    text = re.sub('\s+', ' ', text).strip()
    return text

def remove_urls(text):
    """Remove URLs from the text."""
    url_pattern = re.compile(r'https?://\S+|www\.\S+')
    return url_pattern.sub(r'', text)

def normalize_text(df):
    try:
        df['review'] = df['review'].apply(lower_case)
        df['review'] = df['review'].apply(remove_stop_words)
        df['review'] = df['review'].apply(remove_numbers)
        df['review'] = df['review'].apply(remove_punctuations)
        df['review'] = df['review'].apply(remove_urls)
        df['review'] = df['review'].apply(lemmatization)
        
        return df
    except Exception as e:
        print(f"Error during text normalization: {e}")
        raise

In [33]:
df = normalize_text(df)
df.head()

                                                review sentiment
868  movie good think tiffany amber beautiful liked...  positive
342  see c thomas howell appeared many movie since ...  negative
460  already year eddie murphy longer hot started m...  negative
609  st watched  dir robert elli miller emotional ...  negative
708  looking forward release movie since first hear...  positive

In [34]:
df['sentiment'].value_counts()

sentiment
negative    256
positive    244
Name: count, dtype: int64

In [35]:
x = df['sentiment'].isin(['positive','negative'])
df = df[x]

In [36]:
df['sentiment'] = df['sentiment'].map({'positive': 1, 'negative': 0})
df.head()

                                                review  sentiment
868  movie good think tiffany amber beautiful liked...          1
342  see c thomas howell appeared many movie since ...          0
460  already year eddie murphy longer hot started m...          0
609  st watched  dir robert elli miller emotional ...          0
708  looking forward release movie since first hear...          1

In [38]:
df.isnull().sum()

review       0
sentiment    0
dtype: int64

In [57]:
vectorizer = CountVectorizer(max_features=100)
x = vectorizer.fit_transform(df['review'])
y = df['sentiment']

In [58]:
X_train, X_test, y_train, y_test = train_test_split(x, y, test_size=0.25, random_state=42)

In [59]:
print(X_train.shape[0])
print(X_test.shape[0])

375
125

In [42]:
import dagshub

mlflow.set_tracking_uri('https://dagshub.com/ArupaBarua/Capstone-Project.mlflow')
dagshub.init(repo_owner='ArupaBarua', repo_name='Capstone-Project', mlflow=True)

mlflow.set_experiment("Logistic Regression Baseline")

                                       ❗❗❗ AUTHORIZATION REQUIRED ❗❗❗

c:\Users\arupa\.conda\envs\atlas\lib\site-packages\rich\live.py:260: UserWarning: install "ipywidgets" for Jupyter
support
  warnings.warn('install "ipywidgets" for Jupyter support')

Open the following link in your browser to authorize the client:
https://dagshub.com/login/oauth/authorize?state=7fdc83b2-630b-47a4-b98a-cdc39f1c6082&client_id=32b60ba385aa7cecf24046d8195a71c07dd345d9657977863b52e7748e0f0f28&middleman_request_id=060d2dc5bb6c5ce46a38f105574004b344329b33a40cf83565be755395b6b4df

Accessing as ArupaBarua

Initialized MLflow to track repo "ArupaBarua/Capstone-Project"

Repository ArupaBarua/Capstone-Project initialized!

2026/03/11 17:19:29 INFO mlflow.tracking.fluent: Experiment with name 'Logistic Regression Baseline' does not exist. Creating a new experiment.

<Experiment: artifact_location='mlflow-artifacts:/4b2be7a7ecbb4c0a85d7b3a9537d7f11', creation_time=1773227971168, experiment_id='0', last_update_time=1773227971168, lifecycle_stage='active', name='Logistic Regression Baseline', tags={}, workspace='default'>

In [60]:
import mlflow
import logging
import os
import time
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score

# Configure logging
logging.basicConfig(level=logging.INFO, format="%(asctime)s - %(levelname)s - %(message)s")

logging.info("Starting MLflow run...")

with mlflow.start_run():
    start_time = time.time()
    
    try:
        logging.info("Logging preprocessing parameters...")
        mlflow.log_param("vectorizer", "Bag of Words")
        mlflow.log_param("num_features", 100)
        mlflow.log_param("test_size", 0.25)

        logging.info("Initializing Logistic Regression model...")
        model = LogisticRegression(max_iter=1000)

        logging.info("Fitting the model...")
        model.fit(X_train, y_train)
        logging.info("Model training complete.")

        logging.info("Logging model parameters...")
        mlflow.log_param("model", "Logistic Regression")

        logging.info("Making predictions...")
        y_pred = model.predict(X_test)

        logging.info("Calculating evaluation metrics...")
        accuracy = accuracy_score(y_test, y_pred)
        precision = precision_score(y_test, y_pred)
        recall = recall_score(y_test, y_pred)
        f1 = f1_score(y_test, y_pred)

        logging.info("Logging evaluation metrics...")
        mlflow.log_metric("accuracy", accuracy)
        mlflow.log_metric("precision", precision)
        mlflow.log_metric("recall", recall)
        mlflow.log_metric("f1_score", f1)

        logging.info("Saving and logging the model...")
        mlflow.sklearn.log_model(model, "model")

        # Log execution time
        end_time = time.time()
        logging.info(f"Model training and logging completed in {end_time - start_time:.2f} seconds.")

        # Print the results for verification
        logging.info(f"Accuracy: {accuracy}")
        logging.info(f"Precision: {precision}")
        logging.info(f"Recall: {recall}")
        logging.info(f"F1 Score: {f1}")

    except Exception as e:
        logging.error(f"An error occurred: {e}", exc_info=True)
        raise

2026-03-11 18:01:26,890 - INFO - Starting MLflow run...
2026-03-11 18:01:27,467 - INFO - Logging preprocessing parameters...
2026-03-11 18:01:28,521 - INFO - Initializing Logistic Regression model...
2026-03-11 18:01:28,522 - INFO - Fitting the model...
2026-03-11 18:01:28,559 - INFO - Model training complete.
2026-03-11 18:01:28,560 - INFO - Logging model parameters...
2026-03-11 18:01:28,955 - INFO - Making predictions...
2026-03-11 18:01:28,956 - INFO - Calculating evaluation metrics...
2026-03-11 18:01:28,972 - INFO - Logging evaluation metrics...
2026-03-11 18:01:30,525 - INFO - Saving and logging the model...
2026/03/11 18:01:30 WARNING mlflow.models.model: `artifact_path` is deprecated. Please use `name` instead.
2026/03/11 18:01:34 WARNING mlflow.sklearn: Saving scikit-learn models in the pickle or cloudpickle format requires exercising caution because these formats rely on Python's object serialization mechanism, which can execute arbitrary code during deserialization. The recommended safe alternative is the 'skops' format. For more information, see: https://scikit-learn.org/stable/model_persistence.html
2026-03-11 18:01:44,055 - INFO - Model training and logging completed in 16.59 seconds.
2026-03-11 18:01:44,057 - INFO - Accuracy: 0.544
2026-03-11 18:01:44,059 - INFO - Precision: 0.5254237288135594
2026-03-11 18:01:44,061 - INFO - Recall: 0.5166666666666667
2026-03-11 18:01:44,062 - INFO - F1 Score: 0.5210084033613446

🏃 View run welcoming-skunk-315 at: https://dagshub.com/ArupaBarua/Capstone-Project.mlflow/#/experiments/0/runs/a21163c6cf4248748f1441d641c123fc
🧪 View experiment at: https://dagshub.com/ArupaBarua/Capstone-Project.mlflow/#/experiments/0